name: check-pr
on:
  pull_request:
    branches:
      - master
jobs:
  check-pr:
    name: check-pr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14.2
      - name: go vet
        run: |
          cd snippets
          go vet ./...
      - name: go test
        run: |
          cd snippets
          go test -race ./...
      - name: code compiles on playground, includes tests and has the correct format
        run: |
          ./bin/gophersnippets -pr-check -playground -playground-ua="gophersnippets.com/v1"
